//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCDemo2023.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos
    {
        public int idproducto { get; set; }
        public string nombreProducto { get; set; }
        public Nullable<int> idProveedor { get; set; }
        public Nullable<int> idCategoria { get; set; }
        public string cantidadPorUnidad { get; set; }
        public Nullable<decimal> precioUnidad { get; set; }
        public Nullable<short> unidadesEnExistencia { get; set; }
        public Nullable<short> unidadesEnPedido { get; set; }
        public Nullable<short> nivelNuevoPedido { get; set; }
        public Nullable<short> suspendido { get; set; }
        public string categoriaProducto { get; set; }
    }
}
