//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCDemo2023.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class proveedores
    {
        public int idProveedor { get; set; }
        public string nombreCompañia { get; set; }
        public string nombrecontacto { get; set; }
        public string cargocontacto { get; set; }
        public string direccion { get; set; }
        public string ciudad { get; set; }
        public string region { get; set; }
        public string codPostal { get; set; }
        public string pais { get; set; }
        public string telefono { get; set; }
        public string fax { get; set; }
        public string paginaprincipal { get; set; }
    }
}
